version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: grumpy
      POSTGRES_PASSWORD: grumpy
      POSTGRES_DB: grumpy
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://grumpy:grumpy@db:5432/grumpy
    depends_on:
      - db
volumes:
  pgdata:
